# ==================== ANCHORS/TEMPLATES ====================
x-system-template: &system-template
  # runtime: nvidia
  working_dir: /workspace
  network_mode: host
  ipc: host
  restart: "no"
  stdin_open: true
  tty: true
  environment:
  - DISPLAY=${DISPLAY:-:0}
  - NVIDIA_VISIBLE_DEVICES=all
  - NVIDIA_DRIVER_CAPABILITIES=all
  - QT_X11_NO_MITSHM=1
  - DISABLE_ROS1_EOL_WARNINGS=1
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw

x-x11-volume: &x11-volume
  /tmp/.X11-unix:/tmp/.X11-unix:rw

x-robot-bringup-volume: &robot-bringup-volume
  ./workspaces/robot_bringup:/workspace/src/robot_bringup:rw

x-recorded-data-volume: &recorded-data-volume
  ./data:/data:rw

x-catkin-build-template: &catkin-build-template
  <<: *system-template
  command: catkin build -DCMAKE_BUILD_TYPE=Release
  profiles: ["build"]

x-colcon-build-template: &colcon-build-template
  <<: *system-template
  command: colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release #TODO number of cores, check config file in magpie for colcon defaults
  profiles: ["build"]


# ==================== SERVICES ====================

services:
  # # ==================== UTILITIES ====================

  build_ros1_launcher:
    <<: [*catkin-build-template]
    image: unified_autonomy:ros1_base
    volumes:
      - ./workspaces/ws_ros1_launcher:/workspace
      - *robot-bringup-volume

  # --- ROS1 Bridge (ROS2) ---
  build_ros1_bridge:
    <<: [*colcon-build-template]
    image: unified_autonomy:ros1-bridge-builder
    command: sh -c "cat /ws_ros1_bridge.tgz | tar xzf - -C /workspaces"
    volumes:
      - ./workspaces:/workspaces


  # ==================== CODE ====================
  # * Each workspace is built and launched in its own service
  # * Convenience common map merges are provided for the expected standard use cases
  # * eg. <<: [*catkin-build-template] to inherit common build settings, <<: [*ros1-launch-template]
  # * to inherit common ros 1launch settings ...
  # * Naming convention:
  # *   build service: build_<workspace_name>
  # *   ros1_launch service: ros1_launch_<workspace_name>
  # *   ros2_launch service: ros2_launch_<workspace_name>
  # *   workspace folder: ws_<workspace_name>

  # ==================== DRIVERS ====================

  # IMU
  # --- VectorNav ---
  build_vectornav:
    <<: [*catkin-build-template]
    image: unified_autonomy:ros1_base
    volumes:
      - *robot-bringup-volume
      - ./workspaces/ws_vectornav:/workspace
  
  # LiDAR
  # --- RSLidar SDK ---
  build_rslidar_sdk:
    <<: [*catkin-build-template]
    image: unified_autonomy:ros1_base
    volumes:
      - *robot-bringup-volume
      - ./workspaces/ws_rslidar_sdk:/workspace

  # Radar
  # --- MMWave TI ROS ---
  build_mmwave_ti_ros:
    <<: [*catkin-build-template]
    image: unified_autonomy:ros1_base
    volumes:
      - *robot-bringup-volume
      - ./workspaces/ws_mmwave_ti_ros:/workspace

  # Camera
  # --- Camera Sync ---
  build_cam_sync:
    <<: [*catkin-build-template]
    image: unified_autonomy:ros1_base
    volumes:
      - *robot-bringup-volume
      - ./workspaces/ws_cam_sync:/workspace
  
  # --- ROS GST Bridge (ROS2) ---
  build_ros_gst_bridge:
    <<: [*colcon-build-template]
    image: unified_autonomy:ros2_base
    volumes:
      - ./workspaces/ws_ros_gst_bridge:/workspace

  # ==================== PLANNING ====================

  # Planner
  # --- GBPlanner ---
  build_gbplanner:
    <<: [*catkin-build-template]
    image: unified_autonomy:ros1_gbplanner
    volumes:
      - *robot-bringup-volume
      - ./workspaces/ws_gbplanner:/workspace

  # ==================== SIMULATION ====================

  # --- Simulation ---
  build_sim:
    <<: [*colcon-build-template]
    image: unified_autonomy:ros2_sim
    command: colcon build --cmake-force-configure --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
    volumes:
      - *x11-volume
      - *robot-bringup-volume
      - ./workspaces/ws_sim:/workspace

  # ==================== PERCEPTION ====================

  # Estimation / SLAM
  # --- MIMOSA ---
  build_mimosa:
    <<: [*system-template]
    image: unified_autonomy:ros1_base
    profiles: ["build"]
    command: bash -c "catkin config -DCMAKE_BUILD_TYPE=Release -DGTSAM_POSE3_EXPMAP=ON -DGTSAM_ROT3_EXPMAP=ON -DGTSAM_USE_QUATERNIONS=ON -DGTSAM_USE_SYSTEM_EIGEN=ON -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF -DGTSAM_BUILD_UNSTABLE=ON -DGTSAM_BUILD_EXAMPLES_ALWAYS=OFF -DGTSAM_WITH_TBB=OFF && catkin build"
    volumes:
      - *robot-bringup-volume
      - ./workspaces/ws_mimosa:/workspace

  # --- ETHZ ASL MSF ---
  build_ethzasl_msf:
    <<: [*catkin-build-template]
    image: unified_autonomy:ros1_base
    volumes:
      - *robot-bringup-volume
      - ./workspaces/ws_ethzasl_msf:/workspace

  # --- VLM ---
  build_vlm:
    <<: [*colcon-build-template]
    image: unified_autonomy:ros2_vlm
    runtime: nvidia
    # command: bash -c "source /home/developer/detection_vlm_venv/bin/activate && colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release"
    volumes:
      - *x11-volume
      - *robot-bringup-volume
      - ./workspaces/ws_vlm:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # # # ==================== NMPC ====================

  # # --- NMPC colcon build ---
  build_colconnmpc:
    <<: *colcon-build-template
    image: unified_autonomy:ros2_nmpc
    runtime: nvidia
    command: bash -c "colcon build --cmake-force-configure --cmake-args -DCMAKE_BUILD_TYPE=Release"
    user: developer
    volumes:
      - ./workspaces/ws_nmpc:/workspace
      - *robot-bringup-volume
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=205
  
  build_installnmpc:
    <<: *colcon-build-template
    image: unified_autonomy:ros2_nmpc
    runtime: nvidia
    command: bash -c "pip3 install -e /workspace/src/sdf-nmpc"
    # command: bash -c "colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release"
    user: developer
    volumes:
      - ./workspaces/ws_nmpc:/workspace
      - *robot-bringup-volume
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=205

  build_problemnmpc:
    <<: *colcon-build-template
    image: unified_autonomy:ros2_nmpc
    runtime: nvidia
    command: bash -c "source install/setup.bash && ros2 run sdf_nmpc_ros build_solver.py --ros-args -p cfg:=ros2/nmpc_sim_lidar.yaml"
    user: developer
    volumes:
      - ./workspaces/ws_nmpc:/workspace
      - *robot-bringup-volume
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=205
      - PYTHONPATH=/workspace/src/sdf-nmpc:/home/developer/acados/interfaces/acados_template:${PYTHONPATH}
      - ACADOS_SOURCE_DIR=/home/developer/acados
      # CUDA libs first, then GPU drivers, then acados
      - LD_LIBRARY_PATH=/usr/local/lib:/home/developer/acados/lib:${LD_LIBRARY_PATH}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


  # # ==================== CBF ====================

  build_cbf:
    <<: *colcon-build-template
    image: unified_autonomy:ros2_cbf
    runtime: nvidia
    user: developer
    volumes:
      - ./workspaces/ws_cbf:/workspace
      - *robot-bringup-volume
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=205